set_location_assignment PIN_AB7 -to SRAM_ADDRESS_O[0]
set_location_assignment PIN_AD7 -to SRAM_ADDRESS_O[1]
set_location_assignment PIN_AE7 -to SRAM_ADDRESS_O[2]
set_location_assignment PIN_AC7 -to SRAM_ADDRESS_O[3]
set_location_assignment PIN_AB6 -to SRAM_ADDRESS_O[4]
set_location_assignment PIN_AE6 -to SRAM_ADDRESS_O[5]
set_location_assignment PIN_AB5 -to SRAM_ADDRESS_O[6]
set_location_assignment PIN_AC5 -to SRAM_ADDRESS_O[7]
set_location_assignment PIN_AF5 -to SRAM_ADDRESS_O[8]
set_location_assignment PIN_T7 -to SRAM_ADDRESS_O[9]
set_location_assignment PIN_AF2 -to SRAM_ADDRESS_O[10]
set_location_assignment PIN_AD3 -to SRAM_ADDRESS_O[11]
set_location_assignment PIN_AB4 -to SRAM_ADDRESS_O[12]
set_location_assignment PIN_AC3 -to SRAM_ADDRESS_O[13]
set_location_assignment PIN_AA4 -to SRAM_ADDRESS_O[14]
set_location_assignment PIN_AB11 -to SRAM_ADDRESS_O[15]
set_location_assignment PIN_AC11 -to SRAM_ADDRESS_O[16]
set_location_assignment PIN_AB9 -to SRAM_ADDRESS_O[17]
set_location_assignment PIN_AB8 -to SRAM_ADDRESS_O[18]
set_location_assignment PIN_T8 -to SRAM_ADDRESS_O[19]
set_location_assignment PIN_AH3 -to SRAM_DATA_IO[0]
set_location_assignment PIN_AF4 -to SRAM_DATA_IO[1]
set_location_assignment PIN_AG4 -to SRAM_DATA_IO[2]
set_location_assignment PIN_AH4 -to SRAM_DATA_IO[3]
set_location_assignment PIN_AF6 -to SRAM_DATA_IO[4]
set_location_assignment PIN_AG6 -to SRAM_DATA_IO[5]
set_location_assignment PIN_AH6 -to SRAM_DATA_IO[6]
set_location_assignment PIN_AF7 -to SRAM_DATA_IO[7]
set_location_assignment PIN_AD1 -to SRAM_DATA_IO[8]
set_location_assignment PIN_AD2 -to SRAM_DATA_IO[9]
set_location_assignment PIN_AE2 -to SRAM_DATA_IO[10]
set_location_assignment PIN_AE1 -to SRAM_DATA_IO[11]
set_location_assignment PIN_AE3 -to SRAM_DATA_IO[12]
set_location_assignment PIN_AE4 -to SRAM_DATA_IO[13]
set_location_assignment PIN_AF3 -to SRAM_DATA_IO[14]
set_location_assignment PIN_AG3 -to SRAM_DATA_IO[15]
set_location_assignment PIN_AE8 -to SRAM_WE_N_O
set_location_assignment PIN_AD5 -to SRAM_OE_N_O
set_location_assignment PIN_AC4 -to SRAM_UB_N_O
set_location_assignment PIN_AD4 -to SRAM_LB_N_O
set_location_assignment PIN_AF8 -to SRAM_CE_N_O

set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[16]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[17]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[18]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_ADDRESS_O[19]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[7]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[8]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[9]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[10]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[11]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[12]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[13]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[14]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_DATA_IO[15]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_UB_N_O
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_LB_N_O
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_CE_N_O
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_OE_N_O
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SRAM_WE_N_O

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_ADDRESS_O[19]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_DATA_IO[15]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_UB_N_O
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_LB_N_O
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_CE_N_O
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_OE_N_O
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SRAM_WE_N_O

set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[0]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[1]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[2]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[3]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[4]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[5]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[6]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[7]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[8]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[9]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[10]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[11]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[12]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[13]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[14]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[15]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[16]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[17]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[18]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_ADDRESS_O[19]

set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[0]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[1]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[2]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[3]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[4]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[5]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[6]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[7]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[8]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[9]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[10]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[11]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[12]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[13]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[14]
set_instance_assignment -name SLEW_RATE 2 -to SRAM_DATA_IO[15]

set_instance_assignment -name SLEW_RATE 2 -to SRAM_UB_N_O
set_instance_assignment -name SLEW_RATE 2 -to SRAM_LB_N_O
set_instance_assignment -name SLEW_RATE 2 -to SRAM_CE_N_O
set_instance_assignment -name SLEW_RATE 2 -to SRAM_OE_N_O
set_instance_assignment -name SLEW_RATE 2 -to SRAM_WE_N_O

