set_location_assignment PIN_G19 -to LED_RED_O[0]
set_location_assignment PIN_F19 -to LED_RED_O[1]
set_location_assignment PIN_E19 -to LED_RED_O[2]
set_location_assignment PIN_F21 -to LED_RED_O[3]
set_location_assignment PIN_F18 -to LED_RED_O[4]
set_location_assignment PIN_E18 -to LED_RED_O[5]
set_location_assignment PIN_J19 -to LED_RED_O[6]
set_location_assignment PIN_H19 -to LED_RED_O[7]
set_location_assignment PIN_J17 -to LED_RED_O[8]
set_location_assignment PIN_G17 -to LED_RED_O[9]
set_location_assignment PIN_J15 -to LED_RED_O[10]
set_location_assignment PIN_H16 -to LED_RED_O[11]
set_location_assignment PIN_J16 -to LED_RED_O[12]
set_location_assignment PIN_H17 -to LED_RED_O[13]
set_location_assignment PIN_F15 -to LED_RED_O[14]
set_location_assignment PIN_G15 -to LED_RED_O[15]
set_location_assignment PIN_G16 -to LED_RED_O[16]
set_location_assignment PIN_H15 -to LED_RED_O[17]

set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_RED_O[17]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_RED_O[17]

set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[0]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[1]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[2]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[3]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[4]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[5]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[6]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[7]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[8]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[9]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[10]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[11]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[12]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[13]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[14]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[15]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[16]
set_instance_assignment -name SLEW_RATE 2 -to LED_RED_O[17]

