set_location_assignment PIN_E21 -to LED_GREEN_O[0]
set_location_assignment PIN_E22 -to LED_GREEN_O[1]
set_location_assignment PIN_E25 -to LED_GREEN_O[2]
set_location_assignment PIN_E24 -to LED_GREEN_O[3]
set_location_assignment PIN_H21 -to LED_GREEN_O[4]
set_location_assignment PIN_G20 -to LED_GREEN_O[5]
set_location_assignment PIN_G22 -to LED_GREEN_O[6]
set_location_assignment PIN_G21 -to LED_GREEN_O[7]
set_location_assignment PIN_F17 -to LED_GREEN_O[8]

set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to LED_GREEN_O[8]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to LED_GREEN_O[8]

set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[0]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[1]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[2]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[3]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[4]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[5]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[6]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[7]
set_instance_assignment -name SLEW_RATE 2 -to LED_GREEN_O[8]

