set_location_assignment PIN_AB28 -to SWITCH_I[0]
set_location_assignment PIN_AC28 -to SWITCH_I[1]
set_location_assignment PIN_AC27 -to SWITCH_I[2]
set_location_assignment PIN_AD27 -to SWITCH_I[3]
set_location_assignment PIN_AB27 -to SWITCH_I[4]
set_location_assignment PIN_AC26 -to SWITCH_I[5]
set_location_assignment PIN_AD26 -to SWITCH_I[6]
set_location_assignment PIN_AB26 -to SWITCH_I[7]
set_location_assignment PIN_AC25 -to SWITCH_I[8]
set_location_assignment PIN_AB25 -to SWITCH_I[9]
set_location_assignment PIN_AC24 -to SWITCH_I[10]
set_location_assignment PIN_AB24 -to SWITCH_I[11]
set_location_assignment PIN_AB23 -to SWITCH_I[12]
set_location_assignment PIN_AA24 -to SWITCH_I[13]
set_location_assignment PIN_AA23 -to SWITCH_I[14]
set_location_assignment PIN_AA22 -to SWITCH_I[15]
set_location_assignment PIN_Y24 -to SWITCH_I[16]
set_location_assignment PIN_Y23 -to SWITCH_I[17]

set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[7]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[8]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[9]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[10]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[11]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[12]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[13]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[14]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[15]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[16]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SWITCH_I[17]

set_instance_assignment -name IO_MAXIMUM_TOGGLE_RATE "0 MHz" -to SWITCH_I


