set_location_assignment PIN_G18 -to SEVEN_SEGMENT_N_O[0][0]
set_location_assignment PIN_F22 -to SEVEN_SEGMENT_N_O[0][1]
set_location_assignment PIN_E17 -to SEVEN_SEGMENT_N_O[0][2]
set_location_assignment PIN_L26 -to SEVEN_SEGMENT_N_O[0][3]
set_location_assignment PIN_L25 -to SEVEN_SEGMENT_N_O[0][4]
set_location_assignment PIN_J22 -to SEVEN_SEGMENT_N_O[0][5]
set_location_assignment PIN_H22 -to SEVEN_SEGMENT_N_O[0][6]
set_location_assignment PIN_M24 -to SEVEN_SEGMENT_N_O[1][0]
set_location_assignment PIN_Y22 -to SEVEN_SEGMENT_N_O[1][1]
set_location_assignment PIN_W21 -to SEVEN_SEGMENT_N_O[1][2]
set_location_assignment PIN_W22 -to SEVEN_SEGMENT_N_O[1][3]
set_location_assignment PIN_W25 -to SEVEN_SEGMENT_N_O[1][4]
set_location_assignment PIN_U23 -to SEVEN_SEGMENT_N_O[1][5]
set_location_assignment PIN_U24 -to SEVEN_SEGMENT_N_O[1][6]
set_location_assignment PIN_AA25 -to SEVEN_SEGMENT_N_O[2][0]
set_location_assignment PIN_AA26 -to SEVEN_SEGMENT_N_O[2][1]
set_location_assignment PIN_Y25 -to SEVEN_SEGMENT_N_O[2][2]
set_location_assignment PIN_W26 -to SEVEN_SEGMENT_N_O[2][3]
set_location_assignment PIN_Y26 -to SEVEN_SEGMENT_N_O[2][4]
set_location_assignment PIN_W27 -to SEVEN_SEGMENT_N_O[2][5]
set_location_assignment PIN_W28 -to SEVEN_SEGMENT_N_O[2][6]
set_location_assignment PIN_V21 -to SEVEN_SEGMENT_N_O[3][0]
set_location_assignment PIN_U21 -to SEVEN_SEGMENT_N_O[3][1]
set_location_assignment PIN_AB20 -to SEVEN_SEGMENT_N_O[3][2]
set_location_assignment PIN_AA21 -to SEVEN_SEGMENT_N_O[3][3]
set_location_assignment PIN_AD24 -to SEVEN_SEGMENT_N_O[3][4]
set_location_assignment PIN_AF23 -to SEVEN_SEGMENT_N_O[3][5]
set_location_assignment PIN_Y19 -to SEVEN_SEGMENT_N_O[3][6]
set_location_assignment PIN_AB19 -to SEVEN_SEGMENT_N_O[4][0]
set_location_assignment PIN_AA19 -to SEVEN_SEGMENT_N_O[4][1]
set_location_assignment PIN_AG21 -to SEVEN_SEGMENT_N_O[4][2]
set_location_assignment PIN_AH21 -to SEVEN_SEGMENT_N_O[4][3]
set_location_assignment PIN_AE19 -to SEVEN_SEGMENT_N_O[4][4]
set_location_assignment PIN_AF19 -to SEVEN_SEGMENT_N_O[4][5]
set_location_assignment PIN_AE18 -to SEVEN_SEGMENT_N_O[4][6]
set_location_assignment PIN_AD18 -to SEVEN_SEGMENT_N_O[5][0]
set_location_assignment PIN_AC18 -to SEVEN_SEGMENT_N_O[5][1]
set_location_assignment PIN_AB18 -to SEVEN_SEGMENT_N_O[5][2]
set_location_assignment PIN_AH19 -to SEVEN_SEGMENT_N_O[5][3]
set_location_assignment PIN_AG19 -to SEVEN_SEGMENT_N_O[5][4]
set_location_assignment PIN_AF18 -to SEVEN_SEGMENT_N_O[5][5]
set_location_assignment PIN_AH18 -to SEVEN_SEGMENT_N_O[5][6]
set_location_assignment PIN_AA17 -to SEVEN_SEGMENT_N_O[6][0]
set_location_assignment PIN_AB16 -to SEVEN_SEGMENT_N_O[6][1]
set_location_assignment PIN_AA16 -to SEVEN_SEGMENT_N_O[6][2]
set_location_assignment PIN_AB17 -to SEVEN_SEGMENT_N_O[6][3]
set_location_assignment PIN_AB15 -to SEVEN_SEGMENT_N_O[6][4]
set_location_assignment PIN_AA15 -to SEVEN_SEGMENT_N_O[6][5]
set_location_assignment PIN_AC17 -to SEVEN_SEGMENT_N_O[6][6]
set_location_assignment PIN_AD17 -to SEVEN_SEGMENT_N_O[7][0]
set_location_assignment PIN_AE17 -to SEVEN_SEGMENT_N_O[7][1]
set_location_assignment PIN_AG17 -to SEVEN_SEGMENT_N_O[7][2]
set_location_assignment PIN_AH17 -to SEVEN_SEGMENT_N_O[7][3]
set_location_assignment PIN_AF17 -to SEVEN_SEGMENT_N_O[7][4]
set_location_assignment PIN_AG18 -to SEVEN_SEGMENT_N_O[7][5]
set_location_assignment PIN_AA14 -to SEVEN_SEGMENT_N_O[7][6]

set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[3][0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][0]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][0]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[3][1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][1]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][1]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[3][2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][2]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][2]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[3][3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][3]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][3]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[3][4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][4]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][4]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[3][5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][5]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][5]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[0][6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[1][6]
set_instance_assignment -name IO_STANDARD "2.5 V" -to SEVEN_SEGMENT_N_O[2][6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[3][6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[4][6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[5][6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[6][6]
set_instance_assignment -name IO_STANDARD "3.3-V LVTTL" -to SEVEN_SEGMENT_N_O[7][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[0][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[0][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[1][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[1][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[2][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[2][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[3][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[3][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[4][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[4][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[5][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[5][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[6][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[6][6]

set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 8MA -to SEVEN_SEGMENT_N_O[7][6]

set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][0]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][1]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][2]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][3]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][4]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][5]
set_instance_assignment -name SLEW_RATE 2 -to SEVEN_SEGMENT_N_O[7][6]


